# Generated by Django 4.2.2 on 2023-07-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses_Category', '0004_alter_expensescategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensescategory',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
