# Generated by Django 4.2.2 on 2023-07-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
